openapi: 3.0.0
info:
  description: "JBS api document"
  version: "1.0.0"
  title: "JBS API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "lhj1982@gmail.com"
  license:
    name: MIT
tags:
- name: "oauth"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "script"
  description: "Access to scripts"
- name: "shop"
  description: "Access to shop"
- name: "event"
  description: "Access to script events"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"

servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Internal staging server for testing
  - url: http://jbs.weijinglong.com:3000
    description: Optional server description, e.g. Main (production) server
    

paths:
  /oauth/login:
    post:
      tags:
      - oauth
      summary: "Authorize user"
      description: ""
      operationId: "authrozieUser"
      requestBody: 
        description: Request content
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OauthLogin'
      responses:
        200:
          description: "Success"
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/OauthResponse'
        default:
          description: "Invalid input"
          
  /scripts:
    get:
      tags:
      - "script"
      summary: "List all scripts"
      operationId: "listScripts"
      parameters:
        - in: query
          name: offset
          description: The number of items to skip before starting to collect the result set
          schema:
            type: integer
        - in: query
          name: limit
          description: The numbers of items to return
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScriptsResponse'
        default:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          
  /scripts/{id}:
    get:
      tags:
      - "script"
      summary: "Get one script by id"
      operationId: "getScriptById"
      parameters:
        - in: path
          name: id
          description: script id
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Script'
        default:
          description: 'Default response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  
  /shops:
    get:
      tags:
      - "shop"
      summary: "List all shops"
      operationId: "listShops"
      parameters:
        - in: query
          name: offset
          description: The number of items to skip before starting to collect the result set
          schema:
            type: integer
        - in: query
          name: limit
          description: The numbers of items to return
          schema:
            type: integer
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopsResponse'
        default:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    post:
      tags:
      - "shop"
      summary: "Add new shop"
      operationId: "AddShop"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
                - name
                - key
                - address
                - mobile
                - contactName
                - contactMobile
                - city
              properties:
                name:
                  type: "string"
                key:
                  type: "string"
                address:
                  type: "string"
                mobile:
                  type: "string"
                contactName:
                  type: "string"
                contactMobile:
                  type: "string"
                province:
                  type: "integer"
                district:
                  type: "integer"
                city:
                  type: "string"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
        default:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          
  /shops/{id}:
    get:
      tags:
      - "shop"
      summary: "Get one shop by id"
      operationId: "getShopById"
      parameters:
        - in: path
          name: id
          description: shop id
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
        default:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
                
  /shops/{shopId}/script/{scriptId}:
    post:
      tags:
      - "shop"
      summary: "Add one script to a shop"
      operationId: "addSingleShopScript"
      parameters:
        - in: path
          name: shopId
          required: true
          description: shop id
          schema:
            type: string
        - in: path
          name: scriptId
          required: true
          description: script id
          schema:
            type: string
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
        default:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          
  /events:
    get:
      tags:
      - "event"
      summary: "List all events"
      operationId: "listEvents"
      parameters:
        - in: query
          name: offset
          description: The number of items to skip before starting to collect the result set
          schema:
            type: integer
            format: int32
        - in: query
          name: limit
          description: The numbers of items to return
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsResponse'
        default:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    post:
      tags:
      - "event"
      summary: "Add new event"
      operationId: "addEvent"
      requestBody:
        required: true
        description: event body
        content:
          application/json:
            schema:
              type: "object"
              required:
                - shopId
                - scriptId
                - startTime
                - endTime
                - hostUserId
                - numberOfPersons
                - price
              properties:
                shopId:
                  type: "string"
                scriptId:
                  type: "string"
                startTime:
                  type: "string"
                  format: 'date-time'
                endTime:
                  type: "string"
                  format: 'date-time'
                hostUserId:
                  type: "string"
                hostComment:
                  type: "string"
                numberOfPersons:
                  type: "integer"
                  format: int32
                  minimum: 1
                  maximum: 20
                price:
                  type: "integer"
                  format: int32
              example:
                shopId: '1234'
                scriptId: '1234'
                startTime: '2019-01-01 12:00:00'
                endTime: '2019-01-01 12:00:00'
                hostUserId: '2323'
                numberOfPersons: 1
                price: 100
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        default:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  
  /users:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      security:
        - bearerAuth: []
      requestBody:
        description: "Created user object"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    OauthLogin:
      type: "object"
      properties:
        code:
          type: "string"
        type:
          type: "string"
        nickName:
          type: "string"
      example:
        code: '1234'
        type: 'wxapp'
        nickName: 'test'
    
    OauthResponse:
      type: "object"
      properties:
        openId:
          type: "string"
        accessToken:
          type: "string"
    
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        username:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
        phone:
          type: "string"
        userStatus:
          type: "integer"
          format: "int32"
          description: "User Status"
      xml:
        name: "User"
    
    Script:
      type: "object"
      properties:
        id:
          type: "string"
        key:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        minNumberOfPersons:
          type: "integer"
        maxNumberOfPersons:
          type: "integer"
        duration:
          type: "integer"
        introImage:
          type: "string"
        createdAt: 
          type: "string"
          format: "date-time"
    
    ArrayOfScripts:
      type: "array"
      items:
        $ref: '#/components/schemas/Script'
    
    ScriptsResponse:
      allOf: 
        - $ref: '#/components/schemas/PaginatedDataResponse'
        - 
          type: "object"
          properties:
            data:
              $ref: '#/components/schemas/ArrayOfScripts'
              
    Shop:
      type: "object"
      properties:
        id:
          type: "string"
        key:
          type: "string"
        name:
          type: "string"
        address:
          type: "string"
        mobile:
          type: "string"
        phone:
          type: "string"

    
    ArrayOfShops:
      type: "array"
      items:
        $ref: '#/components/schemas/Shop'
    
    ShopsResponse:
      allOf: 
        - $ref: '#/components/schemas/PaginatedDataResponse'
        - 
          type: "object"
          properties:
            data:
              $ref: '#/components/schemas/ArrayOfShops'  
    
    EventPrice:
      type: "object"
      properties:
        weekdayDayPrice:
          type: "integer"
        weekdayNightPrice:
          type: "integer"
        weekendPrice:
          type: "integer"
    Event:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        startTime:
          type: "string"
        endTime:
          type: "string"
        hostUser:
          type: "object"
          $ref: '#/components/schemas/User'
    
    ArrayOfEvents:
      type: "array"
      items:
        $ref: '#/components/schemas/Event'
    
    EventsResponse:
      allOf: 
        - $ref: '#/components/schemas/PaginatedDataResponse'
        - 
          type: "object"
          properties:
            data:
              $ref: '#/components/schemas/ArrayOfEvents'
      
    PaginatedDataResponse:
      type: "object"
      properties:
        code:
          type: "string"
        pagination:
          type: "object"
          properties:
            offset:
              type: "integer"
            limit:
              type: "integer"
            total:
              type: "integer"
        links:
          type: "object"
          properties:
            next:
              type: "string"
            prev:
              type: "string"
    ApiResponse:
      type: "object"
      properties:
        code:
          type: "string"
          description: "Response code, for example, SUCCESS/FAIL"
        message:
          type: "string"
          description: "Error message, if any"
        data:
          type: "string"
    UnauthorizedError:
      description: Access token is missing or invalid
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"